# Generated by Django 5.0.4 on 2024-04-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_email_member_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
